GamesData = [
  {
    numberOfgame: 1,
    GameName: "Arma 3",
    GameImages: ["01_1.png", "01_2.png", "01_3.png", "01_4.png", "01_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["shooter", "PvP", "Team-based", "Action"],
    Price: 27.5,
    Discount: 5,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [12, "Sep", 2013],
    Systems: ["windows", "macOS", "linux"],
  },
  {
    numberOfgame: 2,
    GameName: "PayDay 2",
    GameImages: ["02_1.png", "02_2.png", "02_3.png", "02_4.png", "02_5.png"],
    title: "Availible Now",
    GameTags: ["shooter", "Online Co-op", "Team-based", "FPS", "Action"],
    Price: 13.99,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "mixed",
    ReleaseDate: [24, "Nov", 2020],
    Systems: ["windows"],
  },
  {
    numberOfgame: 3,
    GameName: "SYNCED",
    GameImages: ["03_1.png", "03_2.png", "03_3.png", "03_4.png", "03_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["Online Co-op", "Team-based", "Battle Royale", "PvP"],
    Price: 0,
    Discount: 10,
    PriceWithDiscount: "",
    Review: "negative",
    ReleaseDate: [8, "Aug", 2021],
    Systems: ["macOS", "linux"],
  },
  {
    numberOfgame: 4,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game", "Action"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 5,
    GameName: "Arma 3",
    GameImages: ["01_1.png", "01_2.png", "01_3.png", "01_4.png", "01_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["shooter", "PvP", "Team-based"],
    Price: 27.5,
    Discount: 80,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [12, "Sep", 2013],
    Systems: ["windows", "macOS", "linux"],
  },
  {
    numberOfgame: 6,
    GameName: "PayDay 2",
    GameImages: ["02_1.png", "02_2.png", "02_3.png", "02_4.png", "02_5.png"],
    title: "Availible Now",
    GameTags: ["shooter", "Online Co-op", "Team-based", "FPS"],
    Price: 13.99,
    Discount: 20,
    PriceWithDiscount: "",
    Review: "mixed",
    ReleaseDate: [24, "Nov", 2020],
    Systems: ["windows"],
  },
  {
    numberOfgame: 7,
    GameName: "SYNCED",
    GameImages: ["03_1.png", "03_2.png", "03_3.png", "03_4.png", "03_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["Online Co-op", "Team-based", "Battle Royale", "PvP"],
    Price: 10,
    Discount: 10,
    PriceWithDiscount: "",
    Review: "negative",
    ReleaseDate: [8, "Aug", 2021],
    Systems: ["macOS", "linux"],
  },
  {
    numberOfgame: 8,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 9,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 0,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 10,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 11,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 93.5,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 12,
    GameName: "Arma 3",
    GameImages: ["01_1.png", "01_2.png", "01_3.png", "01_4.png", "01_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["shooter", "PvP", "Team-based"],
    Price: 0,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [12, "Sep", 2013],
    Systems: ["windows", "macOS", "linux"],
  },
  {
    numberOfgame: 13,
    GameName: "PayDay 2",
    GameImages: ["02_1.png", "02_2.png", "02_3.png", "02_4.png", "02_5.png"],
    title: "Availible Now",
    GameTags: ["shooter", "Online Co-op", "Team-based", "FPS"],
    Price: 0,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "mixed",
    ReleaseDate: [24, "Nov", 2020],
    Systems: ["windows"],
  },
  {
    numberOfgame: 14,
    GameName: "SYNCED",
    GameImages: ["03_1.png", "03_2.png", "03_3.png", "03_4.png", "03_5.png"],
    title: "Recommended Because you played games tagged with",
    GameTags: ["Online Co-op", "Team-based", "Battle Royale", "PvP"],
    Price: 10,
    Discount: 10,
    PriceWithDiscount: "",
    Review: "negative",
    ReleaseDate: [8, "Aug", 2021],
    Systems: ["macOS", "linux"],
  },
  {
    numberOfgame: 15,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 16,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
  {
    numberOfgame: 17,
    GameName: "Red Dead Redemption 2",
    GameImages: ["04_1.png", "04_2.png", "04_3.png", "04_4.png", "04_5.png"],
    title: "Availible Now",
    GameTags: ["Top Seller", "Best Game"],
    Price: 70.87,
    Discount: 0,
    PriceWithDiscount: "",
    Review: "positive",
    ReleaseDate: [5, "Jul", 2023],
    Systems: ["windows", "linux"],
  },
];

//alert(GamesData.length);

/* for (i = 0; i < GamesData[1].GameTags.length; i++) {
  alert(GamesData[1].GameTags[i]);
} */

//alert(GamesData[1].GameTags.length);
